In [16]:
import torch

In [32]:
x = torch.randn(3,requires_grad=True)
x

tensor([-1.0640,  0.5369, -1.0285], requires_grad=True)

In [33]:
#prevent history

#x.requires_grad(False)
#x.detach()
#with torch.no_grad():



In [34]:
#y = x.detach()

In [35]:
#y

tensor([-1.0640,  0.5369, -1.0285])

In [36]:
#stop pytorch from creating gradient and tracking history
with torch.no_grad():
    y = x+2
    print(y)

tensor([0.9360, 2.5369, 0.9715])


- Gradient summation

In [44]:
weight = torch.ones(4,requires_grad=True)

In [50]:
for epoch in range(2):
    model_output = (weight*3).sum()
    
    model_output.backward()
    
    print(weight.grad)
    
    weight.grad.zero_() #reset the gradient

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
