In [1]:
import torch

## Tensor basics

In [15]:
x = torch.empty([2,3])
print(x)

tensor([[8.1802e+20, 6.7704e+22, 8.4637e-07],
        [1.6913e+22, 1.7079e-07, 1.6412e-07]])


In [16]:
x = torch.rand([2,3])
x

tensor([[0.4758, 0.1418, 0.8287],
        [0.3600, 0.6120, 0.6767]])

In [17]:
x = torch.zeros([2,1])
x

tensor([[0.],
        [0.]])

In [19]:
x = torch.ones([2,2])
x

tensor([[1., 1.],
        [1., 1.]])

In [20]:
x.dtype

torch.float32

In [23]:
x.ndim

2

In [25]:
x = torch.ones(2,3 , dtype=torch.bool)
x

tensor([[True, True, True],
        [True, True, True]])

In [27]:
x.size()

torch.Size([2, 3])

#### Tensor from data

In [28]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

#### Operations

In [29]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x , y

(tensor([[0.0048, 0.3735],
         [0.6951, 0.2217]]), tensor([[0.4830, 0.8907],
         [0.0634, 0.1676]]))

In [33]:
z = x+y
z

tensor([[0.4878, 1.2641],
        [0.7586, 0.3893]])

In [34]:
z = torch.add(x,y)
z

tensor([[0.4878, 1.2641],
        [0.7586, 0.3893]])

In [41]:
y.add(x)

tensor([[0.4926, 1.6376],
        [1.4537, 0.6110]])

In [42]:
z = x-y
z

tensor([[-0.4830, -0.8907],
        [-0.0634, -0.1676]])

In [43]:
z  = torch.sub(x,y)
z

tensor([[-0.4830, -0.8907],
        [-0.0634, -0.1676]])

In [44]:
y

tensor([[0.4878, 1.2641],
        [0.7586, 0.3893]])

In [45]:
y.add(z)

tensor([[0.0048, 0.3735],
        [0.6951, 0.2217]])

In [47]:
#to do inplace
y.add_(z)

tensor([[0.0048, 0.3735],
        [0.6951, 0.2217]])

In [48]:
z = x/y
z

tensor([[1., 1.],
        [1., 1.]])

In [49]:
z = torch.div(x,y)
z

tensor([[1., 1.],
        [1., 1.]])

#### Slicing

In [50]:
x= torch.rand(5,3)
x

tensor([[0.7937, 0.2293, 0.6392],
        [0.9908, 0.4508, 0.7251],
        [0.5134, 0.4358, 0.1988],
        [0.7262, 0.7302, 0.1264],
        [0.9082, 0.6866, 0.5719]])

In [56]:
#all rows but only 1 columns
x[:,0]

tensor([0.7937, 0.9908, 0.5134, 0.7262, 0.9082])

In [57]:
#all columns one row
x[0,:]

tensor([0.7937, 0.2293, 0.6392])

In [60]:
#get single element
x[0,1]

tensor(0.2293)

#### reshape

In [62]:
x = torch.rand(4,4)
x

tensor([[0.4362, 0.2984, 0.2517, 0.9636],
        [0.6201, 0.6401, 0.7126, 0.0034],
        [0.3626, 0.5744, 0.2913, 0.4936],
        [0.7434, 0.5598, 0.6905, 0.5160]])

In [64]:
#one dimension
y = x.view(16)
y

tensor([0.4362, 0.2984, 0.2517, 0.9636, 0.6201, 0.6401, 0.7126, 0.0034, 0.3626,
        0.5744, 0.2913, 0.4936, 0.7434, 0.5598, 0.6905, 0.5160])

In [67]:
#2 by 8 tensor
y = x.view(-1,8)
y

tensor([[0.4362, 0.2984, 0.2517, 0.9636, 0.6201, 0.6401, 0.7126, 0.0034],
        [0.3626, 0.5744, 0.2913, 0.4936, 0.7434, 0.5598, 0.6905, 0.5160]])

In [68]:
#two dimension
y = x.view(4,4)
y

tensor([[0.4362, 0.2984, 0.2517, 0.9636],
        [0.6201, 0.6401, 0.7126, 0.0034],
        [0.3626, 0.5744, 0.2913, 0.4936],
        [0.7434, 0.5598, 0.6905, 0.5160]])

In [70]:
#three dimension
y = x.view(2,2,4)
y

tensor([[[0.4362, 0.2984, 0.2517, 0.9636],
         [0.6201, 0.6401, 0.7126, 0.0034]],

        [[0.3626, 0.5744, 0.2913, 0.4936],
         [0.7434, 0.5598, 0.6905, 0.5160]]])

### numpy from tensor

In [71]:
import numpy as np

In [72]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [74]:
#change to numpy
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [75]:
type(b)

numpy.ndarray

In [76]:
##if we modify b or a

a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [77]:
##the numpy array also gets modified
#because they both point to same memory location CPU
b

array([2., 2., 2., 2., 2.], dtype=float32)

#### tensor from numpy

In [78]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [79]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [80]:
a+=1
a

array([2., 2., 2., 2., 2.])

In [82]:
#if we modify a , b also gets modified
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [84]:
##It happens because we are not using cuda toolkit ,
#if we have cuda toolkit then we can run pytorch on GPU
## which will stop pointing to same memory location in CPU

In [ ]:
x = torch.ones(5 , requires_grad=True)